name: dart_flubber
homepage: https://github.com/maxme1/dart_flubber
version: 0.2.0

description: Linear interpolation of open and closed lines for Dart.

environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  test: ^1.16.8
